//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvtoDelo_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class attributes
    {
        public int id { get; set; }
        public string name_rus { get; set; }
        public string name_eng { get; set; }
        public Nullable<int> sort_order { get; set; }
    }
}
