//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvtoDelo_Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AvtoEntities : DbContext
    {
        public AvtoEntities()
            : base("name=AvtoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<attributes> attributes { get; set; }
        public virtual DbSet<category_1lvl> category_1lvl { get; set; }
        public virtual DbSet<category_2lvl> category_2lvl { get; set; }
        public virtual DbSet<category_3lvl> category_3lvl { get; set; }
        public virtual DbSet<complects> complects { get; set; }
        public virtual DbSet<options> options { get; set; }
        public virtual DbSet<product_image> product_image { get; set; }
        public virtual DbSet<product_to_category> product_to_category { get; set; }
        public virtual DbSet<product_to_complect> product_to_complect { get; set; }
        public virtual DbSet<product_to_option> product_to_option { get; set; }
        public virtual DbSet<products> products { get; set; }
    }
}
