//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvtoDelo_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class category_2lvl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public category_2lvl()
        {
            this.category_3lvl = new HashSet<category_3lvl>();
        }
    
        public int id { get; set; }
        public string image { get; set; }
        public string name_rus { get; set; }
        public string name_eng { get; set; }
        public Nullable<int> parent_id { get; set; }
    
        public virtual category_1lvl category_1lvl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<category_3lvl> category_3lvl { get; set; }
    }
}
