//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvtoDelo_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public products()
        {
            this.product_image = new HashSet<product_image>();
            this.product_to_category = new HashSet<product_to_category>();
            this.product_to_complect = new HashSet<product_to_complect>();
            this.product_to_option = new HashSet<product_to_option>();
        }
    
        public int id { get; set; }
        public string model { get; set; }
        public string attributes_rus { get; set; }
        public string attributes_eng { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public string description_rus { get; set; }
        public string description_eng { get; set; }
        public string name_rus { get; set; }
        public string name_eng { get; set; }
        public Nullable<int> complect_group_id { get; set; }
        public Nullable<int> category_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product_image> product_image { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product_to_category> product_to_category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product_to_complect> product_to_complect { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product_to_option> product_to_option { get; set; }
    }
}
